version: "3.9"

services:
  api-gateway:
    image: node:20-alpine
    container_name: api-gateway
    working_dir: /app
    volumes:
      - ../../backend/api-gateway:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    env_file:
      - ../../backend/api-gateway/.env
    depends_on:
      - auth-service
      - user-service

  auth-service:
    build:
      context: ../../backend/services/auth-service
    container_name: auth-service
    expose:
      - "3001"
    env_file:
      - ../../backend/services/auth-service/.env
    depends_on:
      - postgres-auth

  user-service:
    image: node:20-alpine
    container_name: user-service
    working_dir: /app
    volumes:
      - ../../backend/services/user-service:/app
    command: sh -c "npm install && npm run dev"
    env_file:
      - ../../backend/services/user-service/.env
    expose:
      - "3002"
    depends_on:
      - postgres-user

  task-service:
    image: node:20-alpine
    container_name: task-service
    working_dir: /app
    volumes:
      - ../../backend/services/task-service:/app
    command: sh -c "npm install && npm run dev"
    env_file:
      - ../../backend/services/task-service/.env
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5433:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  auth_pg_data:
  user_db_data:
